//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IB2B.Localizacion.UI.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClienteBE", Namespace="http://schemas.datacontract.org/2004/07/IB2B.Localizacion.Service.DataContract.Gl" +
        "obal")]
    [System.SerializableAttribute()]
    public partial class ClienteBE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClienteIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClienteID {
            get {
                return this.ClienteIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ClienteIDField, value) != true)) {
                    this.ClienteIDField = value;
                    this.RaisePropertyChanged("ClienteID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultadoBE", Namespace="http://schemas.datacontract.org/2004/07/IB2B.Localizacion.Service.DataContract.Gl" +
        "obal")]
    [System.SerializableAttribute()]
    public partial class ResultadoBE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResultadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Resultado {
            get {
                return this.ResultadoField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultadoField, value) != true)) {
                    this.ResultadoField = value;
                    this.RaisePropertyChanged("Resultado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DatosSUNATBE", Namespace="http://schemas.datacontract.org/2004/07/IB2B.Localizacion.Service.DataContract.SU" +
        "NAT")]
    [System.SerializableAttribute()]
    public partial class DatosSUNATBE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreComercialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreNaturalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RUCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RazonSocialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoContribuyenteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ValidarRegistroField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreComercial {
            get {
                return this.NombreComercialField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreComercialField, value) != true)) {
                    this.NombreComercialField = value;
                    this.RaisePropertyChanged("NombreComercial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreNatural {
            get {
                return this.NombreNaturalField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreNaturalField, value) != true)) {
                    this.NombreNaturalField = value;
                    this.RaisePropertyChanged("NombreNatural");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RUC {
            get {
                return this.RUCField;
            }
            set {
                if ((object.ReferenceEquals(this.RUCField, value) != true)) {
                    this.RUCField = value;
                    this.RaisePropertyChanged("RUC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RazonSocial {
            get {
                return this.RazonSocialField;
            }
            set {
                if ((object.ReferenceEquals(this.RazonSocialField, value) != true)) {
                    this.RazonSocialField = value;
                    this.RaisePropertyChanged("RazonSocial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoContribuyente {
            get {
                return this.TipoContribuyenteField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoContribuyenteField, value) != true)) {
                    this.TipoContribuyenteField = value;
                    this.RaisePropertyChanged("TipoContribuyente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoDocumento {
            get {
                return this.TipoDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoDocumentoField, value) != true)) {
                    this.TipoDocumentoField = value;
                    this.RaisePropertyChanged("TipoDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ValidarRegistro {
            get {
                return this.ValidarRegistroField;
            }
            set {
                if ((this.ValidarRegistroField.Equals(value) != true)) {
                    this.ValidarRegistroField = value;
                    this.RaisePropertyChanged("ValidarRegistro");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ILocalizacion")]
    public interface ILocalizacion {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocalizacion/RegistrarCliente", ReplyAction="http://tempuri.org/ILocalizacion/RegistrarClienteResponse")]
        IB2B.Localizacion.UI.ServiceReference1.ResultadoBE RegistrarCliente(IB2B.Localizacion.UI.ServiceReference1.ClienteBE pClienteBE, string pAplicacionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocalizacion/RegistrarCliente", ReplyAction="http://tempuri.org/ILocalizacion/RegistrarClienteResponse")]
        System.Threading.Tasks.Task<IB2B.Localizacion.UI.ServiceReference1.ResultadoBE> RegistrarClienteAsync(IB2B.Localizacion.UI.ServiceReference1.ClienteBE pClienteBE, string pAplicacionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocalizacion/GetDataSUNAT", ReplyAction="http://tempuri.org/ILocalizacion/GetDataSUNATResponse")]
        IB2B.Localizacion.UI.ServiceReference1.DatosSUNATBE GetDataSUNAT(string Numero_ruc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocalizacion/GetDataSUNAT", ReplyAction="http://tempuri.org/ILocalizacion/GetDataSUNATResponse")]
        System.Threading.Tasks.Task<IB2B.Localizacion.UI.ServiceReference1.DatosSUNATBE> GetDataSUNATAsync(string Numero_ruc);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILocalizacionChannel : IB2B.Localizacion.UI.ServiceReference1.ILocalizacion, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LocalizacionClient : System.ServiceModel.ClientBase<IB2B.Localizacion.UI.ServiceReference1.ILocalizacion>, IB2B.Localizacion.UI.ServiceReference1.ILocalizacion {
        
        public LocalizacionClient() {
        }
        
        public LocalizacionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LocalizacionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LocalizacionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LocalizacionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public IB2B.Localizacion.UI.ServiceReference1.ResultadoBE RegistrarCliente(IB2B.Localizacion.UI.ServiceReference1.ClienteBE pClienteBE, string pAplicacionId) {
            return base.Channel.RegistrarCliente(pClienteBE, pAplicacionId);
        }
        
        public System.Threading.Tasks.Task<IB2B.Localizacion.UI.ServiceReference1.ResultadoBE> RegistrarClienteAsync(IB2B.Localizacion.UI.ServiceReference1.ClienteBE pClienteBE, string pAplicacionId) {
            return base.Channel.RegistrarClienteAsync(pClienteBE, pAplicacionId);
        }
        
        public IB2B.Localizacion.UI.ServiceReference1.DatosSUNATBE GetDataSUNAT(string Numero_ruc) {
            return base.Channel.GetDataSUNAT(Numero_ruc);
        }
        
        public System.Threading.Tasks.Task<IB2B.Localizacion.UI.ServiceReference1.DatosSUNATBE> GetDataSUNATAsync(string Numero_ruc) {
            return base.Channel.GetDataSUNATAsync(Numero_ruc);
        }
    }
}
